### ISSUE TITLE
Reference error when saving an engagement

### ISSUE THREAD

**Issue by a-pasquale** [necyberteam/cyberteam_drupal#147]
The reference to researcher gives an error, preventing saving the engagement

**Comment by protitude** [comment]
I noticed this when testing. I think the issue is that you have to select a person with a researcher role and it doesn't show a list of only researchers, it lists everyone. I'll look into creating a view for this so it only shows researchers.

**Comment by protitude** [comment]
I created entity reference views for all of these fields in the branch attached to this ticket, but it doesn't appear to be using the view at all. I've spent a chunk of time on this but it doesn't seem to be working. We can discuss if I should spend much more time on this or if the way it works is ok given the user should know the name of the researcher, student, or mentor they are referencing anyways.

**Comment by a-pasquale** [comment]
Ok, let's leave it for now. We can revisit later at some point. I agree it's not worth taking too much time right now.
