### ISSUE TITLE
Fixed bulk action

### ISSUE THREAD

**Issue by protitude** [necyberteam/cyberteam_drupal#298]
On page: /cc-applications

I made several changes to this Plugin, but the following I'm not really sure about:

https://github.com/necyberteam/cyberteam_drupal/blob/358dccde2ea3962e0f1210b83d7a23970873ebd5/web/modules/custom/campuschampions/src/Plugin/Action/ApproveCCAction.php#L35

I commented out this if statement as it referenced a variable that doesn't exist. Please feel free to fix this if I'm taking something out that should be in here.

**Comment by a-pasquale** [comment]
There were several things that needed to be fixed with that VBO. Should be resolved now.
