### ISSUE TITLE
issue with the "git clean" in AmpCommands.php

### ISSUE THREAD

**Issue by jasperlieber** [necyberteam/cyberteam_drupal#302]
Hi @a-pasquale 
 and @protitude 

This is re: https://github.com/necyberteam/cyberteam_drupal/blob/b4fd37cc4532ce85491e1f4079ceea932f42ea2a/blt/src/Blt/Plugin/Commands/AmpCommands.php#L79

I was working with features today, and noticed that the `      $this->_exec( $this->lando() . 'git clean -f tests/behat/features/');
` line was not working.  So I updated it to simply `      $this->_exec( 'git clean -f tests/behat/features/');` -- but this removed all the feature work I had in progress in the `features\templates` directory.  

I see that the idea is to copy features from `templates` into all the other domains, run the tests, and the clean up the copies. 

But seems like we need a different way of doing this while developing features or that `git clean` removes the work in progress (doh!)

Thoughts?

**Comment by protitude** [comment]
Hi @jasperlieber,

I'm sorry you lost your work, I think the easiest solution to this is to remember to at least do a git add on any work you are doing before you run this command. Git clean will only remove un-tracked files, so even if you aren't ready to fully commit your files you should be able to just add them so then git knows to keep them around. I think that's the easiest solution that comes to mind, but I'm open to other ideas if you or @a-pasquale has one.

**Comment by jasperlieber** [comment]
AmpCommands now does a git add
